// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7rtxd9wfgHcooQbEDdgXrkg1qlVyfGOY',
    appId: '1:693414783356:web:d57c473864519eba0adcf9',
    messagingSenderId: '693414783356',
    projectId: 'practice-8abd0',
    authDomain: 'practice-8abd0.firebaseapp.com',
    storageBucket: 'practice-8abd0.appspot.com',
    measurementId: 'G-JVZ6KNH6LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7epMhyO_sOTs2_FT1oNfHySVqkXQ7_F4',
    appId: '1:693414783356:android:3ec69c7e0c3e0d8b0adcf9',
    messagingSenderId: '693414783356',
    projectId: 'practice-8abd0',
    storageBucket: 'practice-8abd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKJ3oHjk0TwEdqeRaz9hGRqNp5Zaeq8wk',
    appId: '1:693414783356:ios:7e82d2176dc478ad0adcf9',
    messagingSenderId: '693414783356',
    projectId: 'practice-8abd0',
    storageBucket: 'practice-8abd0.appspot.com',
    iosBundleId: 'com.sheikhrashi.flutterWithGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKJ3oHjk0TwEdqeRaz9hGRqNp5Zaeq8wk',
    appId: '1:693414783356:ios:7e82d2176dc478ad0adcf9',
    messagingSenderId: '693414783356',
    projectId: 'practice-8abd0',
    storageBucket: 'practice-8abd0.appspot.com',
    iosBundleId: 'com.sheikhrashi.flutterWithGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7rtxd9wfgHcooQbEDdgXrkg1qlVyfGOY',
    appId: '1:693414783356:web:8fb1d7c4a7fe6bfc0adcf9',
    messagingSenderId: '693414783356',
    projectId: 'practice-8abd0',
    authDomain: 'practice-8abd0.firebaseapp.com',
    storageBucket: 'practice-8abd0.appspot.com',
    measurementId: 'G-J0MJXBJS3B',
  );
}
